baseURL = 'https://www.mkmba.nz/'
languageCode = 'en-us'
title = 'MKMBA Ltd. Solving real problems with technology.'
theme = 'default'

[build]
    writeStats = true

[params]
    MetricsHost = "https://metrics.mkmba.nz"
